{{- if and .Values.chatTemplate.enabled .Values.chatTemplate.content }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vllm.fullname" . }}-chat-template
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
data:
  {{ .Values.chatTemplate.filename }}: |
{{ .Values.chatTemplate.content | indent 4 }}
{{- end }}
